pipeline {
    agent any

    stages {

		stage ('clean-infra-objects'){
		                    agent {
                                docker { image 'google/cloud-sdk:latest'
                						args '-v /tmp/:/tmp/ '
                						args '-u root'
                						}
                            }
            steps{

					sh '''
						export DEVSHELL_PROJECT_ID='project-mohemed2087'
						export GOOGLE_APPLICATION_CREDENTIALS=/tmp/project-mohemed2087-ef6a63d68d2f.json
						gcloud auth activate-service-account jenkins-svc@project-mohemed2087.iam.gserviceaccount.com --key-file=/tmp/project-mohemed2087-ef6a63d68d2f.json
						#gsutil rm -r gs://$DEVSHELL_PROJECT_ID 2> /dev/null || true
						#gsutil rm -r gs://$DEVSHELL_PROJECT_ID/dataflow* 2> /dev/null || true
						bq rm -f --table $DEVSHELL_PROJECT_ID:events.stream_appointments
						bq rm -f --table $DEVSHELL_PROJECT_ID:events.batch_appointments
						bq rm -f --dataset $DEVSHELL_PROJECT_ID:events
						gcloud pubsub subscriptions delete projects/project-mohemed2087/subscriptions/mysub
						gcloud pubsub topics delete projects/project-mohemed2087/topics/appointments

						echo 'Cleanup completed.....'
					'''

                }

            }

        }
    }